# Generated by Django 3.2 on 2021-05-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210429_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='留意者')),
                ('content', models.CharField(max_length=255, verbose_name='留言内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
            ],
        ),
    ]
