# Generated by Django 3.2 on 2021-05-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='友链名称')),
                ('url', models.CharField(max_length=128, verbose_name='友链地址')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='呆马', max_length=16, null=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='人类被研究对象', max_length=16, null=None, unique=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('site_name', models.CharField(max_length=64, verbose_name='站点名称')),
                ('pic1', models.FileField(default='img/lunbo/default1.png', upload_to='img/lunbo/')),
                ('pic2', models.FileField(default='img/lunbo/default2.png', upload_to='img/lunbo/')),
                ('pic3', models.FileField(default='img/lunbo/default3.png', upload_to='img/lunbo/')),
                ('pic4', models.FileField(default='img/lunbo/default4.png', upload_to='img/lunbo/')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.link')),
            ],
        ),
    ]
