# Generated by Django 3.2 on 2021-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210515_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bgdoor_name',
            field=models.CharField(default='呆马蓝的后花园', max_length=64, verbose_name='后台站点名称'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_name',
            field=models.CharField(default='呆马蓝的天空', max_length=64, verbose_name='站点名称'),
        ),
    ]
