# Generated by Django 3.2 on 2021-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210515_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hot',
            field=models.BooleanField(default=True),
        ),
    ]
